<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\MediaForge.Search.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Elastic.Clients.Elasticsearch" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="AspNetCore.HealthChecks.Elasticsearch" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
