// <auto-generated />
using System;
using MediaForge.Catalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediaForge.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_slug");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Part", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<int>("OrderMajor")
                        .HasColumnType("integer")
                        .HasColumnName("order_major");

                    b.Property<int>("OrderMinor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("order_minor");

                    b.Property<string>("PartType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("ix_parts_work_id");

                    b.HasIndex("WorkId", "OrderMajor", "OrderMinor")
                        .IsUnique()
                        .HasDatabaseName("ix_parts_work_order");

                    b.ToTable("parts", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.PartAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("MediaAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("media_asset_id");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_order");

                    b.HasKey("Id");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_part_assets_part_id");

                    b.HasIndex("PartId", "MediaAssetId")
                        .IsUnique()
                        .HasDatabaseName("ix_part_assets_part_media_asset");

                    b.ToTable("part_assets", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.PartChapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("EndTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("end_time_seconds");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("PartId")
                        .HasColumnType("uuid")
                        .HasColumnName("part_id");

                    b.Property<double>("StartTimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("start_time_seconds");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("PartId")
                        .HasDatabaseName("ix_part_chapters_part_id");

                    b.ToTable("part_chapters", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("bio");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("photo_url");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_persons_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_series_channel_id");

                    b.ToTable("series", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid")
                        .HasColumnName("channel_id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("language");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_works_channel_id");

                    b.HasIndex("IsPublished")
                        .HasDatabaseName("ix_works_is_published");

                    b.HasIndex("SeriesId")
                        .HasDatabaseName("ix_works_series_id");

                    b.HasIndex("WorkType")
                        .HasDatabaseName("ix_works_work_type");

                    b.ToTable("works", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.WorkContributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_work_contributors_person_id");

                    b.HasIndex("WorkId", "PersonId", "Role")
                        .IsUnique()
                        .HasDatabaseName("ix_work_contributors_work_person_role");

                    b.ToTable("work_contributors", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.WorkGenre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uuid")
                        .HasColumnName("genre_id");

                    b.Property<Guid>("WorkId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkId", "GenreId")
                        .IsUnique()
                        .HasDatabaseName("ix_work_genres_work_genre");

                    b.ToTable("work_genres", (string)null);
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.PartAsset", b =>
                {
                    b.HasOne("MediaForge.Catalog.Domain.Entities.Part", null)
                        .WithMany("_assets")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.PartChapter", b =>
                {
                    b.HasOne("MediaForge.Catalog.Domain.Entities.Part", null)
                        .WithMany("_chapters")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.WorkContributor", b =>
                {
                    b.HasOne("MediaForge.Catalog.Domain.Entities.Work", null)
                        .WithMany("_contributors")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.WorkGenre", b =>
                {
                    b.HasOne("MediaForge.Catalog.Domain.Entities.Work", null)
                        .WithMany("_genres")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Part", b =>
                {
                    b.Navigation("_assets");

                    b.Navigation("_chapters");
                });

            modelBuilder.Entity("MediaForge.Catalog.Domain.Entities.Work", b =>
                {
                    b.Navigation("_contributors");

                    b.Navigation("_genres");
                });
#pragma warning restore 612, 618
        }
    }
}
